### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by 3droot** [INCHEON-CHO/Dynamic-Pruning-with-Feedback#2]
Hi
When I run your script, after validation, I encounter with 
"AttributeError: 'Namespace' object has no attribute 'ensemble'
How can I resolve it?
Line 305 in main.py

**Comment by INCHEON-CHO** [comment]
I'm sorry for the delayed response.
I edited that line.
Please check the new 'main.py'.
Thank you for checking out the error.

**Comment by 3droot** [comment]
Hello,
Thank you for your response.
I checked and the error was resolved. but I have two tips:
1. in the main page of your repository and run part, there must be -- before layer.
2. in the utils.py. Line 201, there is one error "view size is not compatible with input tensor's size and stride" and must add contiguous() before .view().
Thank you.
